#!/bin/bash

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ping ibuki -c 1 &>/dev/null

if [ $? -ne 0 ] ; then
    echo "NOTE: `basename $0` is supposed to be invoked at an ec2 instance... exit"
    exit 1
fi

if [ -z "$JAVA_HOME" ] ; then
    echo "!!! ERROR !!! JAVA_HOME not set... exit"
    exit 1
fi

if [ -z "$HADOOP_HOME" ] ; then
    echo "!!! ERROR !!! HADOOP_HOME not set... exit"
    exit 1
fi

export HADOOP_LOG_DIR=/tmp/hd/logs

export HADOOP_PID_DIR=/tmp

$HADOOP_HOME/sbin/hadoop-daemon.sh \
    --script hdfs stop namenode || exit 1

SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5"
export PDSH_SSH_ARGS_APPEND="$SSH_OPTS"
PDSH="pdsh -S -R ssh -b"
$PDSH -w ^$HADOOP_CONF_DIR/slaves "$HADOOP_HOME/sbin/hadoop-daemon.sh \
    --script hdfs stop datanode" || exit 1

echo ""
echo ""
echo "--------------------"
echo "!!! HD DOWN !!!"

exit 0
