#!/bin/bash -u

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

PREFIX="$HOME/share/yarn-ec2"

YARN="$PREFIX/resource-mngr/exec/yarn_wrapper"

CONF="/tmp/yarn/conf"

ping ibuki -c 1 &>/dev/null

if [ $? -ne 0 ] ; then
    echo "NOTE: `basename $0` is supposed to be invoked at an ec2 instance... exit"
    exit 1
fi

echo "-INFO- listing all yarn nodes... "
parallel-ssh --extra-args "-t -t -q $SSH_OPTS" \
    --timeout 0 \
    --hosts $CONF/boss \
    --user ubuntu \
    --inline \
    $YARN node -all -list || \
exit 1

echo "--------------------"
echo "!!! DONE !!!"

exit 0
